name: "Jest"

on:
  # "master"ブランチへの push または pull request 時にワークフローを実行します
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Actions タブから手動でこのワークフローを実行できます
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Jest
        run: npm install --save-dev jest

      - name: Run Jest tests
        run: npx jest
