# ワークフロー名：CI
name: CI

permissions:
  checks: write
  pull-requests: write

# ワークフローの実行タイミングを制御します
on:
  # "master"ブランチへの push または pull request 時にワークフローを実行します
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Actions タブから手動でこのワークフローを実行できます
  workflow_dispatch:

# ワークフローは1つ以上のジョブで構成され、ジョブは順番または並列で実行できます
jobs:  
  # このワークフローには "build" というジョブが1つ含まれています
  build:
    # ジョブが実行されるランナーの種類
    runs-on: ubuntu-latest
    # steps はジョブ内で実行される一連のタスクです
    steps:
      # actions/checkout@v4 でリポジトリを $GITHUB_WORKSPACE にチェックアウトします
      - uses: actions/checkout@v4

      # Pythonの環境をセットアップ
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # pytest -> JUnit xml形式で結果を出力
      - name: PyTest
        run: |
          python -m pytest . --junit-xml results/pytest.xml
        continue-on-error: true
          
      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results (Python 3.11)
          path: results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v4
        with:
          name: Unit Test Results (Python 3.11)
          path: results


      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: results/*.xml
