name: SonarQube

permissions:
  checks: write
  pull-requests: write
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ sqp_67673b2ae9163f01141fd6fd0a90440ce6cf5c20 }}
          SONAR_HOST_URL: ${{ http://localhost:9000/ }}

      # 以下の行をコメントアウト解除すると、Quality Gate（品質ゲート）が「赤」の場合にジョブを失敗させることができます。
      # これは、品質が基準を満たしていない場合にデプロイを止める用途で使われます。
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
