name: Valgrind Analysis

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    # 下記のブランチは上記のブランチのサブセットである必要があります
    branches: [main]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind

    - name: Compile test.c
      run: gcc -g -o test test.c

    - name: Run Memcheck
      run: |
        valgrind --tool=memcheck \
                 --leak-check=full \
                 --track-origins=yes \
                 --log-file=memcheck.log ./test

    - name: Run Callgrind
      run: |
        valgrind --tool=callgrind \
                 --log-file=callgrind.log ./test

    - name: Run Massif
      run: |
        valgrind --tool=massif \
                 --log-file=massif.log ./test
        ms_print massif.out.* > massif.txt

    - name: Run Helgrind
      run: |
        valgrind --tool=helgrind \
                 --log-file=helgrind.log ./test

    - name: Upload Valgrind logs
      uses: actions/upload-artifact@v3
      with:
        name: valgrind-logs
        path: |
          memcheck.log
          callgrind.log
          massif.log
          massif.txt
          helgrind.log
